---
title: "PS 2"
author: "Aastha"
date: "2/13/2020"
output: html_document
---

```{r}
library(tidyverse)
library(readr)
library(ks)
library(kdensity)
library(data.table)
library(fitdistrplus)
library(ggplot2)
library(gridExtra)
library(ggpubr)
library(dvmisc)


setwd("~/github/empirical-methods/ProblemSets/pset2")


```



```{r message= FALSE warning = FALSE}
dt <- read_csv("nodelmp.csv")
lmp <- dt$lmp
temp <- dt$temp
day <- dt$day
```



1.1
```{r message= FALSE warning = FALSE}


aux          <- dt %>% group_by(day, month, year) %>% summarise(maxP = max(lmp))
dt2          <- semi_join(dt,aux, by = c("lmp"="maxP", "day"="day", "month"="month"))
remove(aux)

plot(dt2$temp, dt2$lmp, xlab = "temperature", ylab = "maximum price", main = "Relationship between maximum price per day and temperature")






```

``` {r message = FALSE warning = FALSE}
for (i in (1:10)) {
  model <- lm(dt2$lmp ~ poly(dt2$temp, i))
  #get_mse(model[i])
}

print( model)

confint(model, level =  0.95) # finding confidence interval of the model at 95% level

plot(fitted(model), residuals(model)) # plotting residuals versus fitted values

get_mse(model)


mse <- vector(mode = "numeric", length(10))
#model <- matrix(0, nrow = 10, ncol = )
for (i in (1:10)) {
  mse[i] <- get_mse(lm(dt2$lmp ~ poly(dt2$temp, i)))
  }
polyDegree <- min(mse)
polyDegree # i obtain optimum polynomial degree to be 7

optModel <- lm(dt2$lmp ~ poly(dt2$temp, 7))
plot(fitted(optModel), residuals(optModel)) # there should be no clear pattern

```

``` {r message = FALSE warning = FALSE}


```

``` {r message = FALSE warning = FALSE}


```


``` {r message = FALSE warning = FALSE}


```


``` {r message = FALSE warning = FALSE}


```


``` {r message = FALSE warning = FALSE}


```


``` {r message = FALSE warning = FALSE}


```


``` {r message = FALSE warning = FALSE}


```


``` {r message = FALSE warning = FALSE}


```

